Import('env')
env = env.Clone()

srcs = Split("""
    GeoPackageTest.cpp
    RialtoWriterTest.cpp
    RialtoReaderTest.cpp
    TileMathTest.cpp
    RialtoTest.cpp
    main.cpp
    """)

cpppath = Split(env.subst("""
    .
    #/include
    $pdal_prefix/include
    #/vendor/gtest-1.7.0/include
    """))

libpath = Split(env.subst("""
    $pdal_prefix/lib
    ../vendor/gtest-1.7.0
    ../src
    """))

libs = Split("""
    pdal_util
    pdalcpp
    sqlite3
    laszip
    rialto
    gtest
    """)

rialtotest = Program('rialtotest', srcs,
    CPPPATH=cpppath, 
    CCFLAGS=env["CCFLAGS"],
    CXXFLAGS=env["CXXFLAGS"],
    LIBPATH=libpath,
    LIBS=libs)

Depends(rialtotest, "../vendor/gtest-1.7.0/libgtest.a")
