Import('env', 'install_prefix')
env = env.Clone()


srcs = Split("""
    Tool.cpp
    InfoTool.cpp
    TranslateTool.cpp
    """)

cpppath = Split(env.subst("""
    .
    #include
    $pdal_prefix/include
    """))

libpath = Split(env.subst("""
    .
    $pdal_prefix/lib
    ../src
    """))

libs = Split("""
    pdal_util
    pdalcpp
    sqlite3
    laszip
    rialto
    tool
    """)

tool = Library('tool', srcs,
    CPPPATH=cpppath, 
    CCFLAGS=env["CCFLAGS"],
    CXXFLAGS=env["CXXFLAGS"],
    LIBPATH=libpath,
    LIBS=libs)
    
rialto_info = Object('rialto_info', 'rialto_info.cpp',
    CPPPATH=cpppath, 
    CCFLAGS=env["CCFLAGS"],
    CXXFLAGS=env["CXXFLAGS"],
    LIBPATH=libpath,
    LIBS=libs)

rialto_translate = Object('rialto_translate', 'rialto_translate.cpp',
    CPPPATH=cpppath, 
    CCFLAGS=env["CCFLAGS"],
    CXXFLAGS=env["CXXFLAGS"],
    LIBPATH=libpath,
    LIBS=libs)

rialto_info = Program('rialto_info', [tool, rialto_info],
    CPPPATH=cpppath, 
    CCFLAGS=env["CCFLAGS"],
    CXXFLAGS=env["CXXFLAGS"],
    LIBPATH=libpath,
    LIBS=libs)

rialto_translate = Program('rialto_translate', [tool, rialto_translate],
    CPPPATH=cpppath, 
    CCFLAGS=env["CCFLAGS"],
    CXXFLAGS=env["CXXFLAGS"],
    LIBPATH=libpath,
    LIBS=libs)
    
Install(install_prefix + "/bin", [rialto_info, rialto_translate])
