Import('env', 'install_prefix')
env = env.Clone()


srcs = Split("""
    Tool.cpp
    main.cpp
    """)

cpppath = Split(env.subst("""
    .
    #include
    $pdal_prefix/include
    """))

libpath = Split(env.subst("""
    $pdal_prefix/lib
    ../src
    """))

libs = Split("""
    pdal_util
    pdalcpp
    sqlite3
    laszip
    rialto
    """)

rialto = Program('rialto', srcs,
    CPPPATH=cpppath, 
    CCFLAGS=env["CCFLAGS"],
    CXXFLAGS=env["CXXFLAGS"],
    LIBPATH=libpath,
    LIBS=libs)
    
Install(install_prefix + "/bin", rialto)
