
Import('env', 'install_prefix')

srcs = Split("""
    GeoPackage.cpp
    GeoPackageWriter.cpp
    GeoPackageCommon.cpp
    RialtoReader.cpp
    GeoPackageManager.cpp
    RialtoWriter.cpp
    GeoPackageReader.cpp
    ViewTileCommon.cpp
    """)

cpppath = Split(env.subst("""
    .
    #include
    $pdal_prefix/include
    """))

libpath = Split(env.subst("""
    $pdal_prefix/lib
    """))

libs = Split("""
    pdal_util
    pdalcpp
    sqlite3
    """)

rialto = SharedLibrary('rialto', srcs,
    CPPPATH=cpppath, 
    CCFLAGS=env["CCFLAGS"],
    CXXFLAGS=env["CXXFLAGS"],
    LIBPATH=libpath,
    LIBS=libs)

headers = Glob("#include/rialto/*.hpp")

Install(install_prefix + "/lib", rialto)
Install(install_prefix + "/include/rialto", headers)
