Import('cppflags')

srcs = Split("""
    GeoPackage.cpp
    GeoPackageWriter.cpp
    GeoPackageCommon.cpp
    RialtoReader.cpp
    GeoPackageManager.cpp
    RialtoWriter.cpp
    GeoPackageReader.cpp
    ViewTileCommon.cpp
    """)

incs = Split("""
    .
    #include
    #../install/pdal/include
    """)

libpath = Split("""
    #../install/pdal/lib
    """)

libs = Split("""
    pdal_util
    pdalcpp
    sqlite3
    """)

rialto = SharedLibrary('rialto', srcs,
    CPPPATH=incs, CPPFLAGS=cppflags,
    LIBS=libs, LIBPATH=libpath)

env = Environment()
env.Install('/tmp/foobar', rialto)
